---
title: "AssessmentPart1"
output: html_notebook
---

```{r}
# Check working path and files
getwd()
list.files(getwd())
```
```{r}
install.packages(c("sf", "tidyverse", "tmap", "tmaptools", "geojsonio", "sp", "reshape2", "stplanr", "leaflet", "broom", "maptools", "stplanr"))
library(tidyverse)
library(sf)
library(tmap)
library(tmaptools)
library(geojsonio)
library(sp)
library(reshape2)
library(stplanr)
library(leaflet)
library(broom)
library(tidyverse)
library(datasets)
library(graphics)
library(grDevices)
library(methods)
library(RColorBrewer)
library(classInt)
library(rgeos)
library(rgdal)
library(geojsonio)
library(classInt)
```

```{r}
#read the shapefile into a simple features object
BirminghamMapMSOA <- read_shape("D:\\GIS\\datas\\Birmingham_CDRC_2011_CensusGeodatapack\\shapefiles\\Birmingham_msoa11.shp", as.sf = TRUE)
```

```{r}
#read Birmingham data attributes
BirminghamData <- read_csv("D:\\GIS\\datas\\Birmingham_CDRC_2011_CensusGeodatapack\\tables\\QS102EW_msoa11.csv", na = "n/a")
#rename the columns in BirminghamData
names(BirminghamData)[2:4] <- c("All_usual_residents","Area(Hectares)", "Density_number_of_persons_per_hectare")
```

```{r}
#join the data from census to the in the Birmingham data frame
BirminghamDataMapMSOA <- append_data(BirminghamMapMSOA,BirminghamData, key.shp = "MSOA11CD", key.data = "GeographyCode", ignore.duplicates = TRUE)
```

```{r}
palette1<-scale_fill_continuous(low="white", high="red", "Density_number_of_persons_per_hectare")
labels<-labs(title="Birmingham Population Density 2011",x="Longitude", y="Latitude")
ggplot()+geom_sf(mapping = aes(geometry=geometry, fill=Density_number_of_persons_per_hectare),data = BirminghamDataMapMSOA)+theme_minimal()+palette1+labels
```

